version: '3.8'

services:
  traefik:
    container_name: inception-traefik
    image: traefik:v2.9.6
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:routers
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal

  client:
    container_name: inception-client
    image: inception-client
    build:
      context: ./services/client
      target: development
    volumes:
      - ./services/client:/app
      - /app/node_modules/
    depends_on:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`localhost`)
      - traefik.http.routers.client.entrypoints=web
      - traefik.http.routers.client.service=client
      - traefik.http.services.client.loadbalancer.server.port=80

  api:
    container_name: inception-api
    image: inception-api
    build:
      context: ./services/api
      target: development
    volumes:
      - ./services/api:/app
      - /app/node_modules/
    depends_on:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.localhost`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.service=api
      - traefik.http.services.api.loadbalancer.server.port=3000

  cms:
    container_name: inception-cms
    image: inception-cms
    build:
      context: ./services/cms
      target: development
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false
    volumes:
      - ./services/cms/config:/app/config
      - ./services/cms/src:/app/src
      - ./services/cms/public/uploads:/app/public/uploads
    depends_on:
      - traefik
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.cms.rule=Host(`cms.localhost`)
      - traefik.http.routers.cms.entrypoints=web
      - traefik.http.routers.cms.service=cms
      - traefik.http.services.cms.loadbalancer.server.port=1337

  db:
    container_name: inception-db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
